### ISSUE TITLE
velodyne poll() timeout

### ISSUE THREAD

**Issue by wawaafan** [jmlago91/Velodyne-HDL-64-S3#1]
I met some problem when I ran these command. The next is my process.
`$roscore`
 
open another terminal

`$ cd ~/catkin_velodyne`
 `$ catkin_make`
 `$ source devel/setup.bash`
 `$rosrun velodyne_driver velodyne_node _model:=HDL-64E-S3` 
  `[ERROR] [1515035654. 066393730]  unknown Velodyne LIDAR model: HDL-64E_S3`
  `[INFO] [1515035654. 067917958]  Velodyne rotating at 600 RPM` 
  `[INFO] [1515035654. 069425008]  publishing 260 packets per scan`
   `[INFO] [1515035654. 077572911]  Reconfigure Request`
  `[INFO] [1515035654. 081693291]  expected frequency: 10.000 (Hz)`
  `[INFO] [1515035654. 083463238]  opening UDP socket: port 2368` 
  `[WARN] [1515035655. 086894380] Velodyne poll( ) timeout`

 I don‘’t know why this happened? 
I checked the solution to the problem, but none of them worked. The solution is as follows:
1. Set the IP  address （I manually set rather than through the terminal）
       source IP address: 192.168.3.43
       destination (DNS) : 192.168.3.255
`ping 192.168.3.43`   I can see it working.
2. running `$ rosrun velodyne_driver vdump 111 eth0` ， I can receive the data.

Could anyone tell me how to solve it? or which step I run out of error?

**Comment by syn1993** [comment]
Hi, I have got the same problem before because I set the wrong IP address.  You can obtain the IP address by WireShark.

**Comment by wawaafan** [comment]
thank you , I have solved the problem according your advise.

**Comment by sarvagyaVatsalSingh** [comment]
Can you please tell how exactly you got the ip from the wireshark. I have the wireshark setup, but it shows me the same ip as 192.168.3.43

**Comment by TZECHIN6** [comment]
@wawaafan  What is the error cause this issue? I also facing it now... the lidar works in few days ago, and it suddenly not working somehow. 

I could ping the LiDAR, and have no idea what is the problem of the IP setting.

**Comment by tersite1** [comment]
Same problem here, but I solved it by checking port number/ run catkin_ws/src VLP16_points.launch and change port number as seen in your Velodyne LiDAR pages Data Port
